# Site settings
title: Eray Aydın
name: Eray Aydın
email: erayaydin2016@gmail.com
location: Konya, Turkey
company: Labkod
company_url: http://labkod.net
github_url: https://github.com/erayaydin
description: Kişisel Geliştirici Blogu
favicon: favicon.png
repository: erayaydin/erayaydin.github.io
url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: aydineray.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Anasayfa

  -
    href: /open-source
    label: Açık Kaynak

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Yerimleri

  -
    href: /about
    label: Hakkımda

# Popular Repo Limit
side_bar_repo_limit: 5

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72941043-4'


# Skills!
skill_web_keywords: [HTML5, CSS3, Javascript, jQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, PHP, Symfony, Bootstrap Framework, Slim, Laravel 4.x, Laravel 5.x, Jekyll, Hugo]
skill_software_keywords: [Java, C, C++, Gtk, Qt, Python, Go, MySQL, SQLite]
