# Site settings
title: Eray Aydın
header-img: media/anasayfa.jpg
email: eray@erayaydin.me
description: "Yazılım ve teknolojiye dair webmaster günlüğü!"
baseurl: ""
url: "http://erayaydin.github.io"
twitter_username: imlinuxbitch
github_username:  erayaydin
facebook_username:  laravel.artisan
disqus: erayaydinorg

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
