# Site settings
title: "Eray Aydın"
email: turkwebdeveloper@gmail.com
description: "Personal Blog."
baseurl: ""
url: "http://erayaydin.github.io/"
title_description: "HTML5 CSS3 PHP Laravel NodeJS Linux C++"
title_image: "https://scontent-ams3-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/10402665_381613885370832_4898829290521034419_n.jpg?oh=ea0e4d3501d85514bdeb34ac128066d5&oe=57B69D14"
google_analytics: "UA-72941043-4"
disqus_account: aydineray
github_repository: https://github.com/erayaydin/erayaydin.github.io
addthis_id: ra-570a0e3daaf721f7
post_limit: 5

# Social usernames/URLs
twitter_username: erayaydi
github_username:  erayaydin
linkedin_link: "#"
google_plus_link: "#"
stackoverflow_link: "#"

# Footer
footer_left: "Design: <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a> | Development: <a href=\"https://twitter.com/imlinuxbitch\">Eray Aydın</a>"
footer_right: "&lt;/&gt; <a href=\"https://github.com/erayaydin/erayaydin.github.io\">Github</a>'ta &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
